version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: sh -c "go build /application/cmd/pososyamba_bot/main.go && /application/main"
    depends_on:
      - redis
    env_file:
      - .env
    tty: true
    stdin_open: true
    volumes:
      - gopath_cache:/go/pkg/mod
      - .:/application:cached

  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  gopath_cache:
  redis_data:
