main_pososyamba: "ПОСОСЯМБА"

prepared_phrases:
  - "Выпускаю пососямбу"
  - "Петусямба пососямба"
  - "Писька пососямба"
  - "Знаешь пососямбу?"
  - "Пососямбы давно не было в чяте ("
  - "паас - пососямба аз а сервис"
  - "челябинская пососямба"
  - "всё, а теперь пососямба"
  - "пососямбу уже пускали в чат?"

gay_names:
  - "faggot"
  - "pidor"
  - "mraz"
  - "petushok"
  - "cocksucker"
  - "analsucker"
  - "pussylicker"
  - "weabo"
  - "cock"
  - "lover"
  - "sinner"
  - "pedorasios"
  - "pidoristo"
  - "pidorasion"
  - "doggo"
  - "volcano"

gay_adjectives:
  - "pretty"
  - "fat"
  - "cool"
  - "sweety"
  - "furryloving"
  - "cuckholdy"
  - "strong"
  - "gentle"
  - "subtle"
  - "foggy"
  - "anime"